on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker hub
        run: docker login --username ${{ secrets.Docker_Username }} --password ${{ secrets.Docker_Token }}

      - name: Building docker image
        run: docker build -t ${{ secrets.Docker_Username }}/proj .

      - name: Pushing to Docker hub
        run: docker push ${{ secrets.Docker_Username }}/proj

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: ./AdelMohamed10/os-project

      - name: Starting minikube
        run: |
          minikube start
      - name: Deploy to web app service
        run: |
          ls -R
          cat deployment.yaml
          kubectl apply -f ./deployment.yaml
          kubectl get pods
          kubectl apply -f NodePort.service.yaml
          kubectl get nodes
          minikube service node-port-service --url
